### PR TITLE
Add support for python 3.5

### PR DESCRIPTION
**Pull request by simonrw**
Add python 3.5 into the `SUPPORTED_ENVS` list

### CODE REVIEW

**Comment by hayd** [comment]
Thanks for sending this, sorry I missed it. Let me try and re-trigger the tests.

**Comment by hayd** [comment]
Hmmm, it seems like 
```
$ conda update -q conda
Fetching package metadata: ..
Solving package specifications: .........................
```
timed out. It didn't used to take anywhere near this long... it's unclear whether that's temporary or a new issue.

See https://travis-ci.org/hayd/ctox/jobs/160863836`

**Comment by mindriot101** [comment]
Perhaps try re-running one of the jobs and see if it fails again? Interestingly the 2.7 job failed after 38 seconds which suggests its not really a timeout issue.

**Comment by hayd** [comment]
(FYI closing+reopening reruns the travis tests)

The cause was two-fold: an old version of miniconda (now we can link to the latest) and colorama's autoreset was quite noisy and pushing over travis' 4mb logfile size limit. It's unclear to me why that wasn't an issue before.

Your commit was merged as part of #8. 👍

**Comment by simonrw** [comment]
Awesome, glad you got to the bottom of it and glad I could help!

**Pull request merged**
